### ISSUE TITLE
Choose of loss function

### ISSUE THREAD

**Issue by OrangeSodahub** [ECCV2024MSE/ECCV_MSE_Teacher#1]
@deponce Hi, for this line:
https://github.com/ECCV2024MSE/ECCV_MSE_Teacher/blob/76f6c300e45babc1e15188a26ed9e7624b34c25c/train_teacher.py#L109
you choose loss function between "MSE" and "CE" via `opt.loss_func.upper`, there is one thing I want to make it clear, did you use the exactly same code to conduct your experiments?
Thanks

**Comment by myl666666** [comment]
Hello, how should I train the student model? Why did I report this error when running the student model? Is the result of the experiment the test result of the student model?
D:\anaconda\envs\qqq\python.exe E:\desktop\ECCV_MSE_Teacher-main\ECCV_MSE_Teacher-main\train_student.py
Traceback (most recent call last):
File "E:\desktop\ECCV_MSE_Teacher-main\ECCV_MSE_Teacher-main\train_student.py", line 354, in <module>
main()
File "E:\desktop\ECCV_MSE_Teacher-main\ECCV_MSE_Teacher-main\train_student.py", line 153, in main
opt = parse_option()
File "E:\desktop\ECCV_MSE_Teacher-main\ECCV_MSE_Teacher-main\train_student.py", line 109, in parse_option
opt.model_t, lr_t = get_teacher_name(opt.path_t)
File "E:\desktop\ECCV_MSE_Teacher-main\ECCV_MSE_Teacher-main\train_student.py", line 132, in get_teacher_name
segments = model_path.split('/')[-2].split('_')
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by OrangeSodahub** [comment]
@myl666666 I'm not the author, don't ask me...

**Comment by myl666666** [comment]
> @deponce Hi, for this line:
> 
> https://github.com/ECCV2024MSE/ECCV_MSE_Teacher/blob/76f6c300e45babc1e15188a26ed9e7624b34c25c/train_teacher.py#L109
> 
> 
> you choose loss function between "MSE" and "CE" via , there is one thing I want to make it clear, did you use the exactly same code to conduct your experiments?
> Thanks`opt.loss_func.upper`

criterion = nn.MSELoss() if opt.loss_func.upper() == 'MSE' else nn.CrossEntropyLoss() ?

**Comment by Linfeng-Ye** [comment]
> [@deponce](https://github.com/deponce) Hi, for this line:
> 
> [ECCV_MSE_Teacher/train_teacher.py](https://github.com/ECCV2024MSE/ECCV_MSE_Teacher/blob/76f6c300e45babc1e15188a26ed9e7624b34c25c/train_teacher.py#L109)
> 
> Line 109 in [76f6c30](/ECCV2024MSE/ECCV_MSE_Teacher/commit/76f6c300e45babc1e15188a26ed9e7624b34c25c)
> 
>  criterion = nn.MSELoss() if opt.loss_func.upper == 'MSE' else nn.CrossEntropyLoss() 
> 
> you choose loss function between "MSE" and "CE" via `opt.loss_func.upper`, there is one thing I want to make it clear, did you use the exactly same code to conduct your experiments?
> Thanks

We are confident that the implementation is correct, as all bash files were tested before running the experiments. However, the released code may not be the final version, as we use GitHub primarily as a backup.
